### ISSUE TITLE
Why the hell am I stuck on demos

### ISSUE THREAD

**Issue by B-17** [jaybo/deepzoom-blog#24]
I'm out here getting pulled out to sea and this  app keeps telling me all about how nice Spain and Portugal are. The waves were getting bigger, but all I know is how much faster a 3 degree course change would give me from Spain to Barbados.

Thanks,

Jacob

(Not quite a dramatization but seriously why doesn't it "play" like it used to last year on the Android app)

Also, registered, hope to see this improved or somehow reverted

**Comment by jaybo** [comment]
The problem seems to be that you've selected a trip (probably Columbus) and it's active.  You need to remove it using one of these methods.

1. Click **Trip.New**.  This erases any existing trip and associated routes.  You can do this on the Trip page, or hit this button:

![image](https://user-images.githubusercontent.com/1607323/236323620-996c4c87-ac3d-46cd-ae89-f5114b6ca2b8.png)

3. Load another trip.
4. You can permanently disable the "demo" dialog on the settings page.

At present, if a trip has been loaded it survives a browser refresh.  Sounds like you're advocating that any existing trip gets cleared out whenever the demo dialog closes.  Or put a "**Trip.New**" button in the demo dialog?

By "play" I assume you mean advance the time.  You can control both starting date using the calendar button to the left of the time readout:

![image](https://user-images.githubusercontent.com/1607323/236324330-ec2cb785-1764-4810-8216-23504cacea4d.png)

And the rate of playback using the button to the right of the time readout:

![image](https://user-images.githubusercontent.com/1607323/236324503-c55cbb6e-b43b-42b2-a017-cba666a35f1a.png)

**Comment by jaybo** [comment]
Version 3.14 provides an easier exit from Demo modes.  Just click the trashcan at the top center of the screen, which is the same as Trip.New.
