### ISSUE TITLE
No update of chart departure and time after saving route

### ISSUE THREAD

**Issue by SyntaxSugarDaddy** [jaybo/deepzoom-blog#25]
Using v3.1.0 w/Chrome (Version 113.0.5672.92 (Official Build) (arm64)) on MacOS -

To replicate the issue, follow these steps:

Create and save a route. After saving the route, make adjustments to the departure time.
Notice that when using the date/time horizontal slider on the chart, the updated departure time is not reflected. This inconsistency occurs when modifying the departure time of a saved route. Despite changing the departure time, the chart fails to display the updated time when utilizing the date/time horizontal slider.

I suggest implementing a more intuitive interface for the departure time slider and speed slider. It would be helpful to have these sliders locked or visually indicate an "edit" option, similar to the route name. As a workaround, I've discovered that clicking the "edit" button for the route, adjusting the departure time, and saving the route enables the chart slider to reflect the updated and saved departure time. This technique works for changes to the route speed too.

To improve usability, there are two possible approaches:

Lock the departure and speed sliders to the route, clearly indicating this in the interface. This ensures that any changes made to the departure time are automatically reflected in the chart. Alternatively, keep the sliders unlocked but enable real-time updates of the chart to reflect the new departure time whenever these sliders are adjusted. Implementing either of these options will enhance the user experience and streamline the process of analyzing the chart with different departure times.

**My preference:** I would like the ability to have an update of the chart in real-time when I freely modify the departure time and speed, without the need to lock or unlock a route. This feature is crucial for me as I rely on the route tool to analyze cause-and-effect relationships with varying departure times. By observing the current changes at different points in a complex route, I can better understand the impact of different factors.

Feature request: Allow the speed setting to be in 0.1 kt increments instead of 0.25 for better granularity on slow moving routes. Thx.

**Comment by jaybo** [comment]
Tackling the easy one first:  You set the speed value to any number (or above 60kn) by just editing the text instead of using the slider:
![image](https://github.com/jaybo/deepzoom-blog/assets/1607323/4e941c21-ed12-48cb-a89c-0a843383d7c5)
Incidentally, you can do this with the date and time values for increased granularity also:
![image](https://github.com/jaybo/deepzoom-blog/assets/1607323/9586ef92-a987-45f7-a427-47da457cfffb)

Now, on to the main issue.

Just to clarify.  You've created a route (I'm not noticing a difference in behavior whether or not the route is then saved).  You're modifying the start time using the slider on the route page.  If you then drag the main time slider does it not correctly reflect the route departure time and arrival time?

I'm assuming that the answer to the above is "yes", but you want the main time slider to *instantaneously* reflect updates while dragging the departure time slider.  Earlier incarnations of DeepZoom have worked this way, but I've disabled this feature since it sometimes triggered automatically switching routes. Which was totally confusing.  

I'll see it I can fix it.

**Comment by SyntaxSugarDaddy** [comment]
That's way better. I think this is how it should work. Thanks!

**Comment by SyntaxSugarDaddy** [comment]
I'll test a few more scenarios out as I have time and will advise.

**Comment by jaybo** [comment]
If **Animation duration** is `Routes.Selected`, I think it always works the way you want.
But if **Animation duration** is `Routes.All` then:
1. If the time slider `now` point is within the selected route, it works.
2. If the time slider `now` point is in another route, there is no visual update. One problem is that after switching routes, the `now` point is at the end of the last route instead of the beginning of the selected route.

Still working on it...

**Comment by jaybo** [comment]
I've put a test version (v3.1.2) on https://deepzoom-test.azurewebsites.net/

This one seems to fix the issues above.  The only thing remaining is that if you adjust the route speed you can advance into the next route, but I'm willing to live with this for now.

**Comment by jaybo** [comment]
I've put a test version (v3.1.3) on https://deepzoom-test.azurewebsites.net/

Should behave the same as v3.1.2.

**Comment by jaybo** [comment]
Marking this fixed in v3.1.4 which was just released.
