### ISSUE TITLE
Current time 1 hour off in Alaska

### ISSUE THREAD

**Issue by Trawler38E** [jaybo/deepzoom-blog#43]
This is probably a known problem but thought I would double check.  Going through Surgis Narrows to Sitka Deep Zoom shows slack current one hour after it occurred.

Thanks for the great tool.

**Comment by jaybo** [comment]
**Here's NOAA**

![image](https://github.com/jaybo/deepzoom-blog/assets/1607323/57146620-edff-4d13-81e0-4f42e6c31691)

**Here's DeepZoom**

![image](https://github.com/jaybo/deepzoom-blog/assets/1607323/b141df15-39d7-463f-9988-e46525e813a5)

So DeepZoom is within 1 minute of NOAA.

I'm guessing your timezone isn't set correctly.  The timezone is established when you first start DeepZoom; thereafter you need to change it appropriate to your local location.  I'm guessing you have it set to Pacific DST instead of Alaska DST.

![image](https://github.com/jaybo/deepzoom-blog/assets/1607323/d33459a5-9727-4611-92d8-a22e9c6898c3)

**Comment by Trawler38E** [comment]
Thanks, I knew it was the time zone issue.  I know Alaska is a one hour time difference from Seattle. I even checked it in my settings which said Los Angles.  That what it always says.  Of course I was wrong.  I am chalking it to aging brain and a little short on sleep on this trip.

Thanks again
________________________________
